import { HOME_BRANDS_MAX_ITEMS } from '../../features/home/utils/home-brand.mapper';
import { HOME_PRODUCT_SECTION_MAX_ITEMS } from '../../features/home/utils/home-product-search.util';
import { PORTAL_THEME_COLOR_DEFAULTS } from '../portal-theme/portal-theme.defaults';
import { LAYOUT_CONFIG } from '../../layout/config/layout.config';
import { PortalConfiguration } from './portal-configuration.model';

/** Defaults aligned with static layout/home config and storefront theme. */
export const DEFAULT_PORTAL_CONFIG: PortalConfiguration = {
  portalNameAr: 'متجر إلكتروني',
  portalNameEn: 'E-Commerce Store',
  portalDescriptionAr: '',
  portalDescriptionEn: '',
  portalBaseUrl: '',
  logoUrl: LAYOUT_CONFIG.branding.logoSrc,
  darkLogoUrl: LAYOUT_CONFIG.branding.logoSrc,
  mobileLogoUrl: LAYOUT_CONFIG.branding.logoSrc,
  faviconUrl: '',
  splashScreenImageUrl: '',
  primaryColor: PORTAL_THEME_COLOR_DEFAULTS.primary,
  secondaryColor: PORTAL_THEME_COLOR_DEFAULTS.secondary,
  accentColor: PORTAL_THEME_COLOR_DEFAULTS.accent,
  backgroundColor: PORTAL_THEME_COLOR_DEFAULTS.mainBackground,
  sectionBackgroundColor: PORTAL_THEME_COLOR_DEFAULTS.sectionBackground,
  mainBackgroundColor: PORTAL_THEME_COLOR_DEFAULTS.mainBackground,
  textColor: PORTAL_THEME_COLOR_DEFAULTS.text,
  headerColor: PORTAL_THEME_COLOR_DEFAULTS.header,
  footerColor: PORTAL_THEME_COLOR_DEFAULTS.footer,
  fontFamilyAr: 'Manrope, system-ui, -apple-system, "Segoe UI", sans-serif',
  fontFamilyEn: 'Manrope, system-ui, -apple-system, "Segoe UI", sans-serif',
  fontSizeBase: 16,
  fontSizeHeading: 30,
  fontSizeSmall: 14,
  showFeaturedProducts: true,
  showBestSellers: true,
  showNewArrivals: true,
  showBrandsSection: true,
  showCategoriesSection: true,
  featuredProductsCount: 3,
  bestSellerCount: HOME_PRODUCT_SECTION_MAX_ITEMS,
  newArrivalCount: HOME_PRODUCT_SECTION_MAX_ITEMS,
  addressAr: '',
  addressEn: '',
  contactInfo: {
    email: '',
    phone: '',
    whatsApp: '',
    supportEmail: '',
    supportPhone: '',
    addressAr: '',
    addressEn: '',
  },
  socialMedia: {
    facebookUrl: '',
    instagramUrl: '',
    twitterUrl: '',
    tikTokUrl: '',
    linkedInUrl: '',
    youTubeUrl: '',
    snapchatUrl: '',
  },
  seo: {
    seoTitleAr: 'متجر إلكتروني',
    seoTitleEn: 'E-Commerce Store',
    seoDescriptionAr: '',
    seoDescriptionEn: '',
    seoKeywords: '',
  },
  mobileSettings: {
    enablePushNotifications: false,
    enableBiometricLogin: false,
    enableGuestCheckout: false,
    enableWishlist: true,
    enableReviews: true,
    enableChatSupport: false,
    forceUpdateVersion: '',
    minimumSupportedVersion: '',
  },
  workflowSettings: {
    enableShipment: true,
    enableDeliveryTracking: true,
    enableReturns: true,
    enableRefunds: true,
    enableCashOnDelivery: true,
    enableOnlinePayment: true,
  },
};
