import { HomePageConfig } from '../models/home.model';

/** Home page structure — edit sections, copy keys, and routes here. */
export const HOME_PAGE_CONFIG: HomePageConfig = {
  hero: {
    imageSrc: '/images/HomeCover.png',
    imageAltKey: 'HOME.HERO.IMAGE_ALT',
    eyebrowKey: 'HOME.HERO.EYEBROW',
    headlineKey: 'HOME.HERO.HEADLINE',
    subtitleKey: 'HOME.HERO.SUBTITLE',
    ctaLabelKey: 'HOME.HERO.CTA',
    ctaRoute: '/shop',
    ctaQuery: { sort: 'featured' },
    secondaryCtaLabelKey: 'HOME.HERO.SECONDARY_CTA',
    secondaryCtaRoute: '/shop',
    secondaryCtaQuery: { category: 'make-up' },
    promoCard: {
      enabled: true,
      eyebrowKey: 'HOME.HERO.PROMO_EYEBROW',
      titleKey: 'HOME.HERO.PROMO_TITLE',
      subtitleKey: 'HOME.HERO.PROMO_SUBTITLE',
      ctaLabelKey: 'HOME.HERO.PROMO_CTA',
      ctaRoute: '/shop',
      ctaQuery: { promo: 'welcome' },
      accentClass: 'home-hero__promo--accent',
    },
  },
  curatedCollections: {
    sectionEyebrowKey: 'HOME.CURATED.EYEBROW',
    sectionTitleKey: 'HOME.CURATED.TITLE',
    items: [
      {
        id: 'cosmetics',
        eyebrowKey: 'HOME.CURATED.COSMETICS_EYEBROW',
        titleKey: 'HOME.CURATED.COSMETICS_TITLE',
        hoverCtaKey: 'HOME.CURATED.CTA',
        imageUrl:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDGVo0lIiop-mFSsEWDMp-njEiBkOqbUFKKQRNii-sZ3w4WeMDk8kN8klAJDSjfc21HMPkfHBvl-f1tuVdhiUSYbw8wd5dKG6gcLuCRC9p447y1HQvvrYEyWEE0RX7aeWlQw6n3-RPP7AHKCcbodv9c-OrLh0QVLf9Fr1bCNu0y5o2InvuBqVzOcqtPsbl3kVrOOwLryRbw_HAs3KChvwQTouMl2UL39nyzLXZ1yabM1eCjFZh2B6h1DiYjz58BELx2gfnBa7F_E9M',
        imageAltKey: 'HOME.CURATED.COSMETICS_ALT',
        route: '/shop',
        queryParams: { category: 'make-up' },
      },
      {
        id: 'derma',
        eyebrowKey: 'HOME.CURATED.DERMA_EYEBROW',
        titleKey: 'HOME.CURATED.DERMA_TITLE',
        hoverCtaKey: 'HOME.CURATED.CTA_DERMA',
        imageUrl:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDdmerfxL1huvtZmwsV2zIsEXlCl2nTScGhUywip_cahD9mtEgKOuR_inWhw4gs4m9b1Wk7H107fUnh6Lg57rc_evyH7NhAGXNiTWLCGAykX_9MWAHo3DJpTvBZv7e57UnvxBdKqo1xGlthoh2VIJ-SI1ItdX7zsR-3LolDlCIk27hwS_FGjaph7ufs3t8Lj05vF7GfRBOMVjC0Zx1O1TzCJb69cALTlZpTgSvvl0bDqrdPJgOyoXDuegPxRPESnsanLrhzk7Hbz3A',
        imageAltKey: 'HOME.CURATED.DERMA_ALT',
        route: '/shop',
        queryParams: { category: 'skin-care' },
      },
      {
        id: 'perfume',
        eyebrowKey: 'HOME.CURATED.PERFUME_EYEBROW',
        titleKey: 'HOME.CURATED.PERFUME_TITLE',
        hoverCtaKey: 'HOME.CURATED.CTA_PERFUME',
        imageUrl:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuCicyOKubdCMsEQScTpegwtDrqz2qFf_A947Ml50BSvP-MtYY9tTkRkkWlIG_AS-AQAes2mT0v69dw6Y6YHyqRy8XsRToXiumC94MrBlfhN5eEtTsB2Ccl9EayPxhpW_Zq13p7G7neaVi9nplUo6iTtnZOsYWvVAu7_2953uWFEz0oxoKq3jY5kd05xJQp1P1cQ_HZcMzVj6FR_s_0Dww46I2tXILEmiIeoT0Sd-fyJQydGsKwB2JvIVLMAF32PECiXUQ3U3bx8DT4',
        imageAltKey: 'HOME.CURATED.PERFUME_ALT',
        route: '/shop',
        queryParams: { category: 'perfume' },
      },
    ],
  },
  categoryShortcuts: [
    {
      id: 'make-up',
      labelKey: 'LAYOUT.NAV.MAKE_UP',
      route: '/shop',
      queryParams: { category: 'make-up' },
      iconClass: 'fa-solid fa-wand-magic-sparkles',
      productCount: 1240,
    },
    {
      id: 'skin-care',
      labelKey: 'LAYOUT.NAV.SKIN_CARE',
      route: '/shop',
      queryParams: { category: 'skin-care' },
      iconClass: 'fa-solid fa-droplet',
      productCount: 980,
    },
    {
      id: 'perfume',
      labelKey: 'LAYOUT.NAV.PERFUME',
      route: '/shop',
      queryParams: { category: 'perfume' },
      iconClass: 'fa-solid fa-spray-can-sparkles',
      productCount: 420,
    },
    {
      id: 'hair-care',
      labelKey: 'LAYOUT.NAV.HAIR_CARE',
      route: '/shop',
      queryParams: { category: 'hair-care' },
      iconClass: 'fa-solid fa-scissors',
      productCount: 560,
    },
    {
      id: 'body-care',
      labelKey: 'LAYOUT.NAV.BODY_CARE',
      route: '/shop',
      queryParams: { category: 'body-care' },
      iconClass: 'fa-solid fa-spa',
      productCount: 710,
    },
    {
      id: 'brands',
      labelKey: 'LAYOUT.NAV.BRANDS',
      route: '/brands',
      iconClass: 'fa-solid fa-tags',
      productCount: 85,
    },
  ],
  productSections: [
    {
      id: 'most-searched',
      titleKey: 'HOME.MOST_SEARCHED.TITLE',
      subtitleKey: 'HOME.MOST_SEARCHED.SUBTITLE',
      viewAllRoute: '/shop',
      viewAllQuery: { sort: 'popular' },
      layout: 'scroll',
    },
    {
      id: 'best-sellers',
      titleKey: 'HOME.BEST_SELLERS.TITLE',
      subtitleKey: 'HOME.BEST_SELLERS.SUBTITLE',
      viewAllRoute: '/shop',
      viewAllQuery: { sort: 'bestsellers' },
      layout: 'grid',
    },
    {
      id: 'new-arrivals',
      titleKey: 'HOME.NEW_ARRIVALS.TITLE',
      subtitleKey: 'HOME.NEW_ARRIVALS.SUBTITLE',
      viewAllRoute: '/shop',
      viewAllQuery: { sort: 'new' },
      layout: 'grid',
    },
  ],
  offers: [
    {
      id: 'welcome',
      titleKey: 'HOME.OFFERS.WELCOME_TITLE',
      subtitleKey: 'HOME.OFFERS.WELCOME_SUBTITLE',
      discountLabelKey: 'HOME.OFFERS.WELCOME_DISCOUNT',
      discountPercent: 10,
      ctaLabelKey: 'HOME.OFFERS.SHOP_NOW',
      route: '/shop',
      queryParams: { promo: 'welcome' },
      theme: 'accent',
    },
    {
      id: 'bazar',
      titleKey: 'HOME.OFFERS.BAZAR_TITLE',
      subtitleKey: 'HOME.OFFERS.BAZAR_SUBTITLE',
      ctaLabelKey: 'HOME.OFFERS.VIEW_DEALS',
      route: '/shop',
      queryParams: { category: 'bazar' },
      theme: 'primary',
    },
    {
      id: 'derma',
      titleKey: 'HOME.OFFERS.DERMA_TITLE',
      subtitleKey: 'HOME.OFFERS.DERMA_SUBTITLE',
      ctaLabelKey: 'HOME.OFFERS.EXPLORE',
      route: '/shop',
      queryParams: { category: 'skin-care' },
      theme: 'dark',
    },
  ],
  brands: {
    titleKey: 'HOME.BRANDS.TITLE',
    subtitleKey: 'HOME.BRANDS.SUBTITLE',
    viewAllRoute: '/brands',
    items: [
      { id: 'lrp', nameKey: 'HOME.BRANDS.LRP', route: '/brands', queryParams: { brand: 'la-roche-posay' }, initials: 'LP' },
      { id: 'eucerin', nameKey: 'HOME.BRANDS.EUCERIN', route: '/brands', queryParams: { brand: 'eucerin' }, initials: 'EU' },
      { id: 'cerave', nameKey: 'HOME.BRANDS.CERAVE', route: '/brands', queryParams: { brand: 'cerave' }, initials: 'CV' },
      { id: 'isdin', nameKey: 'HOME.BRANDS.ISDIN', route: '/brands', queryParams: { brand: 'isdin' }, initials: 'IS' },
      { id: 'garnier', nameKey: 'HOME.BRANDS.GARNIER', route: '/brands', queryParams: { brand: 'garnier' }, initials: 'GA' },
      { id: 'essence', nameKey: 'HOME.BRANDS.ESSENCE', route: '/brands', queryParams: { brand: 'essence' }, initials: 'ES' },
      { id: 'babaria', nameKey: 'HOME.BRANDS.BABARIA', route: '/brands', queryParams: { brand: 'babaria' }, initials: 'BA' },
      { id: 'avene', nameKey: 'HOME.BRANDS.AVENE', route: '/brands', queryParams: { brand: 'avene' }, initials: 'AV' },
    ],
  },
  trustBadges: [
    {
      id: 'delivery',
      labelKey: 'HOME.TRUST.DELIVERY_TITLE',
      descriptionKey: 'HOME.TRUST.DELIVERY_DESC',
      iconClass: 'fa-solid fa-truck-fast',
    },
    {
      id: 'payment',
      labelKey: 'HOME.TRUST.PAYMENT_TITLE',
      descriptionKey: 'HOME.TRUST.PAYMENT_DESC',
      iconClass: 'fa-solid fa-lock',
    },
    {
      id: 'returns',
      labelKey: 'HOME.TRUST.RETURNS_TITLE',
      descriptionKey: 'HOME.TRUST.RETURNS_DESC',
      iconClass: 'fa-solid fa-rotate-left',
    },
    {
      id: 'support',
      labelKey: 'HOME.TRUST.SUPPORT_TITLE',
      descriptionKey: 'HOME.TRUST.SUPPORT_DESC',
      iconClass: 'fa-solid fa-headset',
    },
  ],
};
